### ISSUE TITLE
Calibration test failure

### ISSUE THREAD

**Issue by jan1za** [EntelectChallenge/2017-Battleships#12]
Running the compiled game engine provided (https://github.com/EntelectChallenge/2017-Battleships/releases/latest) on i7 Windows 10, I get the following errors in the log Failed to run calibration test System.ComponentModel.Win32Exception (0x80004005)

The error happens during phase 1.
Attached log files, 

[Phase 1 - Round 0.zip](https://github.com/EntelectChallenge/2017-Battleships/files/948008/Phase.1.-.Round.0.zip)

It appears to be looking for BotCalibrationDotNet.exe which is missing from both the code base and the pre-compiled application.

Subsequent errors are that, because of the JIT compiler the first time the exe loads it fails as it takes to long after that it is quick. It then fails to place its boats in the first round phase 1 and gets a penalty.

**Comment by jan1za** [comment]
Related to this, because the reference bot was forced time out, due to the failed calibration, subsequent rounds show Failed to process command FireShotCommand for player JohnGameEngine.Exceptions.InvalidCommandException: All your ships must be placed before you are allowed to shoot
   at GameEngine.Commands.PlayerCommands.FireShotCommand.PerformCommand(GameMap gameMap, BattleshipPlayer player) in W:\Projects\100k\2017\Github\2017-Batteships\GameEngine\Battleships\GameEngine\Commands\PlayerCommands\FireShotCommand.cs:line 45
   at GameEngine.Engine.GameRoundProcessor.ProcessPlayerCommands() in W:\Projects\100k\2017\Github\2017-Batteships\GameEngine\Battleships\GameEngine\Engine\GameRoundProcessor.cs:line 113

The rules say that you should get 5 turns to place your ships, yet this fails after the first attemp. Attaching the entire game log.

[2017-04-21 20-18-09-309.zip](https://github.com/EntelectChallenge/2017-Battleships/files/948019/2017-04-21.20-18-09-309.zip)

**Comment by jan1za** [comment]
It appears to be looking for BotCalibrationDotNet.exe which is missing from both the code base and the pre-compiled application.

**Comment by aodendaal** [comment]
I'm also running Windows 10 on an i7. I just downloaded "Game.Engine.-.Version.1.0.0.zip" extracted it and ran "RunGame.bat" without any changes and it worked as expected.

I checked your logs (thanks for uploading) and indeed it seems you're missing something.

Maybe try download it again, extract and run again?

**Comment by jan1za** [comment]
Nope still does it downloaded the latest from https://github.com/EntelectChallenge/2017-Battleships/releases/tag/1.0.0 there are 3 logs in each round engine.log and then log files for the bots A and B, I am looking at Phase 1 - Round 0 - A - log.txt. 

Issue is DotNetRunning.cs specifies on line 63 it requires BotCalibrationDotNet.exe which does not exist in the same app or the code in git. 
The bot calibration is called by StartGame(GameMap gameState) in TestHarness.TestHarnesses.Bot, line 75. BotRunning project does have a folder called Calibrations but it is empty.


I can confirm that this happens in both the precompiled executable and the master branch on git.

I followed your exact sequence "I just downloaded "Game.Engine.-.Version.1.0.0.zip" extracted it and ran "RunGame.bat" without any changes and it worked as expected."

**Comment by jan1za** [comment]
To confirm, the test harness is working without the calibration running, its just the first time the exe is run it runs slower than the subsequent times. I just thought you should know what's in the logs. ie the Failed to run calibration test System.ComponentModel.Win32Exception (0x80004005)

**Comment by EntelectChallenge** [comment]
Hi jan1za,

The calibration bots have not been made yet.  We are waiting for all the sample bots for all languages to be submitted before we make the calibration bots.  The calibration bots not being there should not affect the game in any way however.

**Comment by jan1za** [comment]
Thats cool, thank you for the feed back. As I said the game is working as expected,
