### ISSUE TITLE
C# SampleBot and ReferenceBot Timeouts

### ISSUE THREAD

**Issue by jpvdm1** [EntelectChallenge/2017-Battleships#38]
Hi,

I'm getting timeouts with the C# SampleBot and ReferenceBot.

Contents of log.txt:

16-05-2017 09:19:30:673 - I: 	Your bot exceeded the maximum execution time
16-05-2017 09:19:30:673 - E: 	Bot time limit exceeded BotRunner.Exceptions.TimeLimitExceededException: Time limit exceeded by 00:00:00.8102689
   at TestHarness.TestHarnesses.Bot.BotRunner.RunBot() in W:\Projects\100k\2017\Github\2017-Batteships\GameEngine\Battleships\BotRunner\Harness\Bot\BotRunner.cs:line 96
   at TestHarness.TestHarnesses.Bot.BotHarness.RunBotAndGetNextMove() in W:\Projects\100k\2017\Github\2017-Batteships\GameEngine\Battleships\BotRunner\Harness\Bot\BotHarness.cs:line 142

My machine specifications:
HDD = 250GB SSD
RAM = 8GB DDR3
CPU = Intel Core i7 4712MQ @ 2.30Ghz
OS    = Windows 10 Pro
Anti-Virus = Trend Micro
Visual Studio = 2015 Pro

Any ideas why this is happening?

**Comment by EntelectChallenge** [comment]
Hi,

Is it constantly timing out? Or only sometimes?

Haven’t had this issue before, are you able to run to the Java reference bot?

Kid regards,
Gerhard Smit

**Comment by jpvdm1** [comment]
Constantly on this machine. I will try to replicate on a different machine later today.
Haven't tried the Java Reference bot.

**Comment by EntelectChallenge** [comment]
Hi,

Can you attached the log file for us so we can have a better look at the events leading up to the timeout?

**Comment by jpvdm1** [comment]
I have attached the Replay folder.
[2017-05-16 09-18-08-059.zip](https://github.com/EntelectChallenge/2017-Battleships/files/1007496/2017-05-16.09-18-08-059.zip)
