### ISSUE TITLE
Ship Placement

### ISSUE THREAD

**Issue by EntelectChallenge** [EntelectChallenge/2017-Battleships#8]
The reference bot often also fails to place his ships, and after mine failed many times I decided to test it manually. I took the place.txt file, and placed the ships manually on a Excel sheet, paying close attention to use the Direction modifiers as they are coded in the Game Engine. It works out every time, but the Game Engine fails with errors like Cell(9,1) has no neighbours to the east, which regardless of whether East is left or right, there should be a cell there!

**Comment by Ocky-Public** [comment]
Hey, cell(9,1) has no neighbors to the east since it is against the right side wall on a 10x10 grid. From my testing of this to visualize the board properly, coordinates seem to start in the bottom left corner.

**Comment by gkmauer** [comment]
After fixing my East/West mixup, I think there might still be issues with horizontal ships that are flush against the East (right hand) side. I got the following example on a large map:

22-04-2017 16:37:29:541 - E: 	Failed to process command PlaceShipCommand for player GustavGameEngine.Exceptions.InvalidCommandException: There was a problem during the placement of player's Gustav ships, the round will be played over ---> System.InvalidOperationException: This cell does not have a neighbour in the East direction
   at Domain.Maps.Cell.Neighbour(Direction direction) in W:\Projects\100k\2017\Github\2017-Batteships\GameEngine\Battleships\Domain\Maps\Cell.cs:line 71
   at Domain.Ships.Ship.CanPlace(Point point, Direction direction, PlayerMap playerMap) in W:\Projects\100k\2017\Github\2017-Batteships\GameEngine\Battleships\Domain\Ships\Ship.cs:line 90
   at Domain.Maps.PlayerMap.CanPlace(Ship ship, Point point, Direction direction) in W:\Projects\100k\2017\Github\2017-Batteships\GameEngine\Battleships\Domain\Maps\PlayerMap.cs:line 87
   at Domain.Games.GameMap.CanPlace(PlayerType playerType, ShipType shipType, Point coordinate, Direction direction) in W:\Projects\100k\2017\Github\2017-Batteships\GameEngine\Battleships\Domain\Games\GameMap.cs:line 116
   at GameEngine.Commands.PlayerCommands.PlaceShipCommand.PerformCommand(GameMap gameMap, BattleshipPlayer player) in W:\Projects\100k\2017\Github\2017-Batteships\GameEngine\Battleships\GameEngine\Commands\PlayerCommands\PlaceShipCommand.cs:line 43
   --- End of inner exception stack trace ---
   at GameEngine.Commands.PlayerCommands.PlaceShipCommand.PerformCommand(GameMap gameMap, BattleshipPlayer player) in W:\Projects\100k\2017\Github\2017-Batteships\GameEngine\Battleships\GameEngine\Commands\PlayerCommands\PlaceShipCommand.cs:line 47
   at GameEngine.Engine.GameRoundProcessor.ProcessPlayerCommands() in W:\Projects\100k\2017\Github\2017-Batteships\GameEngine\Battleships\GameEngine\Engine\GameRoundProcessor.cs:line 113

22-04-2017 16:37:29:510 - I: 	Output from bot: Placement instructions: 
22-04-2017 16:37:29:510 - I: 	Output from bot: Carrier 9 2 East
22-04-2017 16:37:29:510 - I: 	Output from bot: Battleship 10 7 East
22-04-2017 16:37:29:510 - I: 	Output from bot: Cruiser 2 0 East
22-04-2017 16:37:29:510 - I: 	Output from bot: Submarine 9 12 East
22-04-2017 16:37:29:510 - I: 	Output from bot: Destroyer 1 6 East
22-04-2017 16:37:29:510 - I: 	Output from bot: 
22-04-2017 16:37:29:510 - I: 	Output from bot: 
22-04-2017 16:37:29:510 - I: 	Output from bot: ~~~~~~~~~~~~~~
22-04-2017 16:37:29:510 - I: 	Output from bot: ~~~~~~~~~SSS~~
22-04-2017 16:37:29:510 - I: 	Output from bot: ~~~~~~~~~~~~~~
22-04-2017 16:37:29:510 - I: 	Output from bot: ~~~~~~~~~~~~~~
22-04-2017 16:37:29:510 - I: 	Output from bot: ~~~~~~~~~~~~~~
22-04-2017 16:37:29:510 - I: 	Output from bot: ~~~~~~~~~~~~~~
22-04-2017 16:37:29:510 - I: 	Output from bot: ~~~~~~~~~~BBBB
22-04-2017 16:37:29:510 - I: 	Output from bot: ~DD~~~~~~~~~~~
22-04-2017 16:37:29:510 - I: 	Output from bot: ~~~~~~~~~~~~~~
22-04-2017 16:37:29:510 - I: 	Output from bot: ~~~~~~~~~~~~~~
22-04-2017 16:37:29:510 - I: 	Output from bot: ~~~~~~~~~~~~~~
22-04-2017 16:37:29:510 - I: 	Output from bot: ~~~~~~~~~CCCCC
22-04-2017 16:37:29:510 - I: 	Output from bot: ~~~~~~~~~~~~~~
22-04-2017 16:37:29:510 - I: 	Output from bot: ~~RRR~~~~~~~~~

**Comment by Ocky-Public** [comment]
Hey, after looking at this in more detail it appears to happen when you place the tail end of a ship against any border. An easy way to avoid it is to just flip the direction you place the ship in.

Found the code that is causing this so i'll look at getting a PR going this weekend.
